#!/bin/zsh

batStatus=`cat /sys/class/power_supply/BAT0/status`
batLap=`cat /sys/class/power_supply/BAT0/capacity`

if [ $batStatus = 'Charging' ]
then
	batIcon=" "
elif [ $batStatus = 'Full' ]
then
	batIcon=" "
elif
then
	case $batLap in
		[0-9]|1[0-5])
			batIcon=" "
			;;
		1[6-9]|2[0-5])
			batIcon=" "
			;;
		2[6-9]|3[0-9]|4[0])
			batIcon=" "
			;;
		4[1-9]|5[0-9])
			batIcon=" "
			;;
		6[0-9]|7[0-9]|8[0-4])
			batIcon=" "
			;;
		8[5-0]|9[0-9])
			batIcon=" "
			;;
#			*)
#				batIcon=" "
#				;;
	esac
fi

echo -e "$batIcon$batLap%"
